title: Technical Documentation
description: Technical Documentation Flanders Smart Data Space
remote_theme: just-the-docs/just-the-docs@v0.5.3

url: https://just-the-docs.github.io

favicon_ico: "https://openldes.org/assets/assets/images/favicon.ico"

kramdown:
  parse_block_html: true

callouts:
  note:
    title: Note
    color: yellow
  highlight:
    title: Tip
    color: green

# Define Jekyll collections
collections:
  basic:
    permalink: "/:collection/:path"
    output: true
  pipeline:
    permalink: "/:collection/:path"
    output: true
  publisher:
    permalink: "/:collection/:path"
    output: true
  consumer:
    permalink: "/:collection/:path"
    output: true
  intermediary:
    permalink: "/:collection/:path"
    output: true

# Enable or disable the site search
# Supports true (default) or false
search_enabled: true
search:
  # Split pages into sections that can be searched individually
  # Supports 1 - 6, default: 2
  heading_level: 2
  # Maximum amount of previews per search result
  # Default: 3
  previews: 2
  # Maximum amount of words to display before a matched word in the preview
  # Default: 5
  preview_words_before: 3
  # Maximum amount of words to display after a matched word in the preview
  # Default: 10
  preview_words_after: 3
  # Set the search token separator
  # Default: /[\s\-/]+/
  # Example: enable support for hyphenated search words
  tokenizer_separator: /[\s/]+/
  # Display the relative url in search results
  # Supports true (default) or false
  rel_url: true
  # Enable or disable the search button that appears in the bottom right corner of every page
  # Supports true or false (default)
  button: false

just_the_docs:
  collections:
    basic:
      name: Basic concepts
    pipeline:
      name: General Pipeline
    publisher:
      name: Publishing Pipeline
    consumer:
      name: Consuming Pipeline
    intermediary:
      name: Intermediary Pipeline

enable_copy_code_button: true

footer_content: " "

header_pages: [test.html]

# Footer "Edit this page on GitHub" link text
gh_edit_link: true # show or hide edit this page link
# gh_edit_link_text: "Contribute on GitHub"
# gh_edit_repository: "https://github.com/OpenLDES/Linked-Data-Interactions" # the github URL for your repo
gh_edit_branch: "develop" # the branch that your docs is served from
gh_edit_source: docs # the source that your files originate from
gh_edit_view_mode: "tree" # "tree" or "edit" if you want the user to jump into the editor immediately

mermaid:
  # Version of mermaid library
  # Pick an available version from https://cdn.jsdelivr.net/npm/mermaid/
  version: "9.1.3"
